### PR TITLE
First draft of login and registration pages and routing - checks and feedback included

### LINKED ISSUE #2: Page for Login
Create a form component with:
- [x] Email field with validation (non-empty, email format)
- [x] Password field with hidden input and validation (non-empty, min/max length)
- [x] "Submit" button that is disabled (not clickable) until the user provides valid input to all fields
- [x] Clicking the submit button triggers a POST request to the /login endpoint with **encrypted** body
- [x] If credentials are not valid, reset the form and display a specific error with a suggestion for the relevant next step:
   - [x]  Error 1: Email not found - suggest a link to the registration page, reset entire login form
   - [x]  Error 2: Wrong password - suggest a link to the reset password page, reset password field only
- [x] "Login" Button / link to the button page

Ideally the email and password fields should be customizable components that can be reused for the registration page.

### LINKED ISSUE #3: Page for Registration
Create a form component with:
- [x] Email field with validation (non-empty, email format)
- [x] Password field with hidden input and validation (non-empty, min/max length, at least 1 letter/number)
- [x] Repeat password field with hidden input and validation (identical with the 1st password field)
- [x] "Submit" button that is disabled (not clickable) until the user provides valid input to all fields
- [x] Clicking the submit button triggers a POST request to the /register endpoint with **encrypted** body
- [x] "Forgot Password" Button / link to the password reset page
- [x] "Register" Button / link to the registration page

Ideally the email and password fields should be customizable components that can be reused for the login page.

Extension:
- [ ] Add dynamic email field validation - when the user finished typing (before they clicked the submit button), make an API call with the current input to check if the email already exists in the database. If the email exists, mark the input as invalid (to keep the submit button disabled), display an error message and suggest a link to the login page. [Note: might need to create a dedicated endpoint for email validation in the backend]

### PR DESCRIPTION
**Pull request by JoeMei0603**
Closes #2 
Closes #3 

Update: I am working on the validation and some other minor changes as well like the code smells etc. this is just a PR so that everyone can take a first look at the pages.

IMPORTANT: Since we don't want to waste any emails, make sure to COMMENT OUT:

       Line 23 in AdminController (no email sent) 
       Lines 32 and 33 in AdminService (no authentication required yet)

### CODE REVIEW

File: src/pages/Login.tsx [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+    const navigate = useNavigate()
+    const toast = useToast()
+    const [show, setShow] = React.useState(false)
+    const handleClick = () => setShow(!show)
+
+    const tryLogin = async (values: FormikValues) => {
+        const adminData = await post('/login', values)
+
+        if (!response.ok) {
+            toast({ title: adminData.message, description: response.status, status: response.ok ? 'success' : 'error' })
```
Comment (ofvalentine) [inline src/pages/Login.tsx:31]: Can be simplified to status: 'error'

File: src/pages/Login.tsx [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+            return
+        }
+
+        toast({ title: 'Logged in', description: response.status, status: response.ok ? 'success' : 'error' })
```
Comment (ofvalentine) [inline src/pages/Login.tsx:35]: We can remove the return on line 32 and nest lines 34+35 inside an else clause (also simplifying to status: 'success')

File: src/pages/Registration.tsx [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+            toast({ title: 'Email already taken - are you already registered?', description: response.status, status: response.ok ? 'success' : 'error' })
+            return
+        }
+        navigate('/dashboard')
+    }
+
+
+    const schema = object({ email: string().required().matches(/^.*((?=.*[@]){1}).*$/, "Not a valid email"),
+        password: string().required().matches(
+            /^.*(?=.{6,})((?=.*[!@#$%^&*()\-_=+{};:,<.>?]){1})(?=.*\d)((?=.*[a-z]){1})((?=.*[A-Z]){1}).*$/,
```
Comment (ofvalentine) [inline src/pages/Registration.tsx:49]: Yup has a built-in email validation so we can replace the regex pattern with string().email()

File: src/pages/Registration.tsx [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+                            <VStack spacing={2} width={600}>
+                                <Heading color='blue.700'>Registration</Heading>
+                                <HStack>
+                                    <Text color='blue.700' fontSize="s" align={"center"}>Register in order to gain full access to all features of GroupMatcher.</Text>
+                                </HStack>
+                            </VStack>
+                            <VStack spacing={8} width={400}>
+                                <Field name='email' children={(fieldProps: FieldProps) =>
+                                    <FormControl isInvalid={fieldProps.meta.value && fieldProps.meta.error}>
+                                        <FormLabel color='blue.700' htmlFor='email'><strong>Email address</strong></FormLabel>
```
Comment (ofvalentine) [inline src/pages/Registration.tsx:69]: - The htmlFor will automatically be defined with the name='...' value passed to Field so we don't need to set it explicitely
- We can use chakra's attribute fontWeight={600} or fontWeight='bold' instead of the <strong> tag

File: src/pages/Login.tsx [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+import { Field, FieldProps, Form, Formik, FormikProps, FormikValues } from 'formik'
+import React from 'react'
+import { useNavigate } from 'react-router-dom'
+import { useFetch } from 'use-http'
+
+export default function Login() {
+    const {post, response} = useFetch()
+    const navigate = useNavigate()
+    const toast = useToast()
+    const [show, setShow] = React.useState(false)
```
Comment (ofvalentine) [inline src/pages/Login.tsx:24]: Chakra UI has a really convenient hook for handling exactly these cases of toggling true/false:
https://chakra-ui.com/docs/styled-system/utility-hooks/use-boolean

File: src/pages/Registration.tsx [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+                                                <Button h='1.75rem' size='sm' onClick={handleClick}>
+                                                    {show ? 'Hide' : 'Show'}
+                                                </Button>
+                                            </InputRightAddon>
+                                        </InputGroup>
+                                        <FormErrorMessage justifyContent='end'>{fieldProps.meta.value && fieldProps.meta.error}</FormErrorMessage>
+                                    </FormControl>} />
+                            </VStack>
+                            <Button colorScheme='blue' width={200} type='submit'
+                                    disabled={!formProps.values.email || !formProps.values.password ||
```
Comment (ofvalentine) [inline src/pages/Registration.tsx:104]: Since we added yup validation we can generally check if the values are valid via formProps.errors.[field name], and this will return a falsy value if there are no errors  for the field or it will return the error message (as we defined in the yup schema) if there is any error.
Specifically here we can do:
disabled={formProps.errors.email || formProps.errors.password}
or to check all fields at once:
disabled={!!formProps.errors}

**Review by ofvalentine — APPROVED** [review]
Looks good! I included a few comments about minor syntax issues that can be changed later.
